name: 'GitOps Pull Request Environment'
description: 'Used for creating, updating or deleting PR environments through a GitOps repo.'
inputs:
  action:
    description: 'Action to perform'
    required: true
  changes:
    description: 'Changes to be applied'
    required: false
  github-token:
    description: 'GitHub token'
    required: true
  gitops-repo:
    description: 'GitOps repo to update'
    required: true
  gitops-project:
    description: 'GitOps project'
    required: true
  gitops-pr-environment:
    description: 'GitOps environment to be created'
    required: true 
  commit-email:
    description: 'Email address to use for the commit'
    required: true
  commit-name:
    description: 'Name to use for the commit'
    required: true
  commit-message:
    description: 'Message to use for the commit'
    required: true

runs:
  using: "composite"
  steps:
  - name: Checkout GitOps Repository
    uses: actions/checkout@v3
    with:
      repository: ${{ inputs.gitops-repo }}
      ref: 'main'
      token: ${{ inputs.github-token }}
      path: gitops
  - name: Create a new overlays environment
    if: ${{ inputs.action == 'opened' }}
    shell: bash
    run: |
      cd gitops/pullrequests/${{ inputs.gitops-project }}
      mkdir -p overlays/${{ inputs.gitops-pr-environment }}
      cp overlays/template.yaml overlays/${{ inputs.gitops-pr-environment }}/kustomization.yaml
      sed -i "s/<PR_NUMBER>/${{ inputs.gitops-pr-environment }}/g" overlays/${{ inputs.gitops-pr-environment }}/kustomization.yaml
      # TODO Add to main kustomization.yaml
  - name: Update overlays environment
    if: ${{ inputs.action == 'synchronize' || inputs.action == 'opened' }}
    uses: fjogeleit/yaml-update-action@main
    with:
      valueFile: 'gitops/pullrequests/${{ inputs.gitops-project }}/overlays/${{ inputs.gitops-pr-environment }}/kustomization.yaml'
      changes: ${{ inputs.changes }}
      commitChange: false
  - name: Delete an overlay environment
    if: ${{ inputs.action == 'closed' }}
    shell: bash
    run: |
      cd gitops/pullrequests/${{ inputs.gitops-project }}
      rm -rf overlays/${{ inputs.gitops-pr-environment }}
      # TODO Remove from main kustomization.yaml
  - name: Commit and push changes
    shell: bash
    run: |
      cd gitops
      git config --global user.email "${{ inputs.commit-email }}"
      git config --global user.name "${{ inputs.commit-name }}"
      git add .
      git commit -m "${{ inputs.commit-message }}"
      git push