name: 'GitOps Pull Request Environment'
description: 'Used for creating, updating or deleting PR environments through a GitOps repo.'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  gitops-repo:
    description: 'GitOps repo to update'
    required: true
  gitops-project:
    description: 'GitOps project'
    required: true
  gitops-pr-environment:
    description: 'GitOps environment to be created'
    required: true 
  commit-email:
    description: 'Email address to use for the commit'
    required: true
  commit-name:
    description: 'Name to use for the commit'
    required: true
  commit-message:
    description: 'Message to use for the commit'
    required: true

runs:
  using: "composite"
  steps:
  - name: Checkout GitOps Repository
    uses: actions/checkout@v3
    with:
      repository: ${{ inputs.gitops-repo }}
      ref: 'main'
      token: ${{ inputs.github-token }}
      path: gitops
  - name: Make new directory and copy template file with replaced pr version
    shell: bash
    run: |
      cd gitops/pullrequests/${{ inputs.gitops-project }}
      mkdir -p overlays/${{ inputs.gitops-pr-environment }}
      cp overlays/template.yaml overlays/${{ inputs.gitops-pr-environment }}/kustomization.yaml
      sed -i "s/<PR_NUMBER>/${{ inputs.gitops-pr-environment }}/g" overlays/${{ inputs.gitops-pr-environment }}/kustomization.yaml
  - name: Commit and push changes
    shell: bash
    run: |
      cd gitops
      git config --global user.email "${{ inputs.commit-email }}"
      git config --global user.name "${{ inputs.commit-name }}"
      git add .
      git commit -m "${{ inputs.commit-message }}"
      git push

  # - uses: fjogeleit/yaml-update-action@main
  #   with:
  #     branch: deployment/${{ inputs.gitops-pr-branch }}
  #     targetBranch: main
  #     masterBranchName: main
  #     createPR: true
  #     commitChange: true
  #     repository: ${{ inputs.gitops-repo }}
  #     message: ${{ inputs.commit-message }}
  #     workDir: gitops
  #     valueFile: ${{ inputs.gitops-file }}
  #     propertyPath: ${{ inputs.gitops-key }}
  #     value: ${{ inputs.gitops-value }}
  #     token: ${{ inputs.github-token }}
